version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dental_system_app
    restart: unless-stopped
    # El archivo Dockerfile que tienes usa /var/www/html como base
    working_dir: /var/www/html
    volumes:
      # Enlazamos toda tu carpeta viva de Windows a la de Linux
      - ./:/var/www/html
    env_file:
      - .env
    networks:
      - dental_network

  nginx:
    image: nginx:alpine
    container_name: dental_system_nginx
    restart: unless-stopped
    ports:
      # Expone el puerto 80 a tu computadora Windows (http://localhost)
      - "80:80"
    volumes:
      # Nginx necesita leer la carpeta public para servir tus imágenes y assets de Vite
      - ./:/var/www/html:ro
      # Montamos la configuración de tu Nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dental_network

networks:
  dental_network:
    driver: bridge
